In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
type(array_list)

numpy.ndarray

In [4]:
array_list.dtype

dtype('<U1')

In [5]:
type(list_)

list

In [6]:
'''
Yes,there is a difference in data types variable(list_) is a "list type of data" and array_list is a "numpy type of data in array"
'''

'\nYes,there is a difference in data types variable(list_) is a "list type of data" and array_list is a "numpy type of data in array"\n'

# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [7]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

for i in list_:
    print(f"The data type of {i} is {type(i)}")

for i in array_list:
    print(f"The data type of {i} is {type(i)}")

The data type of 1 is <class 'str'>
The data type of 2 is <class 'str'>
The data type of 3 is <class 'str'>
The data type of 4 is <class 'str'>
The data type of 5 is <class 'str'>
The data type of 1 is <class 'numpy.str_'>
The data type of 2 is <class 'numpy.str_'>
The data type of 3 is <class 'numpy.str_'>
The data type of 4 is <class 'numpy.str_'>
The data type of 5 is <class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:

# array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

In [8]:
array_list = np.array(object = list_, dtype = int)

In [9]:
array_list

array([1, 2, 3, 4, 5])

In [10]:
type(array_list)

numpy.ndarray

In [11]:
array_list.dtype

dtype('int64')

In [12]:
list_

['1', '2', '3', '4', '5']

In [14]:
'''
Yes,there is a difference between them list_ has string datatype and array_list changes its datatype str to int.
'''

'\nYes,there is a difference between them list_ has string datatype and array_list changes its datatype str to int.\n'

# Q4.Consider the below code to answer further questions:
# import numpy as np
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
# num_array = np.array(object = num_list)
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [15]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [17]:
num_array.shape

(2, 3)

In [18]:
num_array.size

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])